import assert from "node:assert/strict";
import { test } from "node:test";
import { applyGameAction, initialGame } from "../src/modules/game/state.ts";
import { battleSnapshot } from "../src/modules/game/battle.ts";

test("answers are ordered, immutable and idempotent; future answer keys are not exposed", () => {
  const game = initialGame();
  applyGameAction(game, { action: "start", expeditionId: "tutorial", chapter: 1 });
  const battleId = game.battle!.id;
  const questions = game.expeditions[0].regions[0].questionBank!;
  const before = battleSnapshot(game)!;
  assert.equal("answerIndex" in before.question!, false);
  assert.equal("explanation" in before.question!, false);
  assert.equal(before.feedback, null);
  assert.throws(() => applyGameAction(game, { action: "answer", battleId, questionId: questions[1].id, selectedIndex: 1 }));
  assert.throws(() => applyGameAction(game, { action: "answer", battleId: "another-account", questionId: questions[0].id, selectedIndex: 0 }));
  for (const selectedIndex of [-1, 4, 1.5, "0", null]) assert.throws(() => applyGameAction(game, { action: "answer", battleId, questionId: questions[0].id, selectedIndex }));
  const answer = { action: "answer", battleId, questionId: questions[0].id, selectedIndex: questions[0].answerIndex };
  applyGameAction(game, answer);
  applyGameAction(game, answer);
  assert.equal(game.battle!.answers.length, 1);
  assert.equal(battleSnapshot(game)!.feedback!.explanation, questions[0].explanation);
  assert.throws(() => applyGameAction(game, { ...answer, selectedIndex: 3 }), /already been answered/);
  applyGameAction(game, { action: "start", expeditionId: "tutorial", chapter: 1 });
  assert.equal(game.battle!.id, battleId);
  assert.equal(game.battle!.answers.length, 1);
  assert.throws(() => applyGameAction(game, { action: "complete" }));
  assert.throws(() => applyGameAction(game, { action: "complete", battleId }), /Answer every question/);
  assert.equal(game.gold, 1450);
});

test("failed attempts save results without rewards; a passing retry rewards once", () => {
  const game = initialGame();
  applyGameAction(game, { action: "start", expeditionId: "tutorial", chapter: 1 });
  const oldId = game.battle!.id;
  const questions = game.expeditions[0].regions[0].questionBank!;
  for (const question of questions) applyGameAction(game, { action: "answer", battleId: oldId, questionId: question.id, selectedIndex: (question.answerIndex + 1) % 4 });
  applyGameAction(game, { action: "complete", battleId: oldId });
  assert.equal(game.battle!.status, "failed");
  assert.equal(game.gold, 1450);
  assert.equal(game.expeditions[0].progress, 0);
  assert.equal(game.battleHistory!.length, 1);
  applyGameAction(game, { action: "start", expeditionId: "tutorial", chapter: 1 });
  const newId = game.battle!.id;
  assert.notEqual(newId, oldId);
  assert.throws(() => applyGameAction(game, { action: "complete", battleId: oldId }));
  questions.forEach((question, index) => applyGameAction(game, { action: "answer", battleId: newId, questionId: question.id, selectedIndex: index === 0 ? (question.answerIndex + 1) % 4 : question.answerIndex }));
  applyGameAction(game, { action: "complete", battleId: newId });
  assert.equal(game.battle!.status, "passed");
  assert.equal(game.gold, 1900);
  assert.equal(game.xp, 100);
  applyGameAction(game, { action: "complete", battleId: newId });
  assert.equal(game.battleHistory!.length, 2);
  assert.equal(game.gold, 1900);
  applyGameAction(game, { action: "start", expeditionId: "tutorial", chapter: 1 });
  const replayId = game.battle!.id;
  questions.forEach((question) => applyGameAction(game, { action: "answer", battleId: replayId, questionId: question.id, selectedIndex: question.answerIndex }));
  applyGameAction(game, { action: "complete", battleId: replayId });
  assert.equal(game.gold, 1900);
  assert.equal(game.battle!.goldReward, 0);
});
