export const art = {
  logo: require("../assets/stitch/art-00.png"),
  landscape: require("../assets/stitch/art-01.png"),
  forest: require("../assets/stitch/art-02.png"),
  chest: require("../assets/stitch/art-03.png"),
  robe: require("../assets/stitch/art-04.png"),
  quill: require("../assets/stitch/art-05.png"),
  shield: require("../assets/stitch/art-06.png"),
  avatar: require("../assets/stitch/art-07.png"),
  cap: require("../assets/stitch/art-08.png"),
  staff: require("../assets/stitch/art-09.png"),
  noviceRobe: require("../assets/stitch/art-10.png"),
  amulet: require("../assets/stitch/art-11.png"),
  mage: require("../assets/stitch/art-12.png"),
  goblin: require("../assets/stitch/art-13.png"),
};

export const icons = {
  hub: require("../assets/icon/home.png"),
  map: require("../assets/icon/map.png"),
  bazaar: require("../assets/icon/chest.png"),
  armory: require("../assets/icon/backpack.png"),
  coins: require("../assets/icon/coins.png"),
  gems: require("../assets/icon/gems.png"),
  exp: require("../assets/icon/exp.png"),
};

export const miniIcons = {
  crossedSwords: require("../assets/mini icon/sliced/crossed-swords.png"),
  oakTome: require("../assets/mini icon/sliced/oak-tome.png"),
  hpPotion: require("../assets/mini icon/sliced/hp-potion.png"),
  chest: require("../assets/mini icon/sliced/chest.png"),
  heart: require("../assets/mini icon/sliced/heart.png"),
  water: require("../assets/mini icon/sliced/water.png"),
  goldenSwords: require("../assets/mini icon/sliced/golden-swords.png"),
  shield: require("../assets/mini icon/sliced/shield.png"),
  clueBulb: require("../assets/mini icon/sliced/clue-bulb.png"),
  attackBolt: require("../assets/mini icon/sliced/attack-bolt.png"),
  healPlus: require("../assets/mini icon/sliced/heal-plus.png"),
  retryScroll: require("../assets/mini icon/sliced/retry-scroll.png"),
};

export const gui = {
  background: require("../assets/GUI/background.webp"),
  header: require("../assets/GUI/header.webp"),
  navbar: require("../assets/GUI/navbar.webp"),
  scroll9: {
    topLeft: require("../assets/GUI/scroll-9/top-left.webp"),
    top: require("../assets/GUI/scroll-9/top.webp"),
    topRight: require("../assets/GUI/scroll-9/top-right.webp"),
    left: require("../assets/GUI/scroll-9/left.webp"),
    center: require("../assets/GUI/scroll-9/center.webp"),
    right: require("../assets/GUI/scroll-9/right.webp"),
    bottomLeft: require("../assets/GUI/scroll-9/bottom-left.webp"),
    bottom: require("../assets/GUI/scroll-9/bottom.webp"),
    bottomRight: require("../assets/GUI/scroll-9/bottom-right.webp"),
  },
  bagTop9: {
    topLeft: require("../assets/GUI/bag-scroll-top-9/top-left.png"),
    top: require("../assets/GUI/bag-scroll-top-9/top.png"),
    topRight: require("../assets/GUI/bag-scroll-top-9/top-right.png"),
    left: require("../assets/GUI/bag-scroll-top-9/left.png"),
    center: require("../assets/GUI/bag-scroll-top-9/center.png"),
    right: require("../assets/GUI/bag-scroll-top-9/right.png"),
    bottomLeft: require("../assets/GUI/bag-scroll-top-9/bottom-left.png"),
    bottom: require("../assets/GUI/bag-scroll-top-9/bottom.png"),
    bottomRight: require("../assets/GUI/bag-scroll-top-9/bottom-right.png"),
  },
  bagBottom9: {
    topLeft: require("../assets/GUI/bag-scroll-bottom-9/top-left.png"),
    top: require("../assets/GUI/bag-scroll-bottom-9/top.png"),
    topRight: require("../assets/GUI/bag-scroll-bottom-9/top-right.png"),
    left: require("../assets/GUI/bag-scroll-bottom-9/left.png"),
    center: require("../assets/GUI/bag-scroll-bottom-9/center.png"),
    right: require("../assets/GUI/bag-scroll-bottom-9/right.png"),
    bottomLeft: require("../assets/GUI/bag-scroll-bottom-9/bottom-left.png"),
    bottom: require("../assets/GUI/bag-scroll-bottom-9/bottom.png"),
    bottomRight: require("../assets/GUI/bag-scroll-bottom-9/bottom-right.png"),
  },
  expeditionCard9: {
    topLeft: require("../assets/GUI/expedition-card-9/top-left.webp"),
    top: require("../assets/GUI/expedition-card-9/top.webp"),
    topRight: require("../assets/GUI/expedition-card-9/top-right.webp"),
    left: require("../assets/GUI/expedition-card-9/left.webp"),
    center: require("../assets/GUI/expedition-card-9/center.webp"),
    right: require("../assets/GUI/expedition-card-9/right.webp"),
    bottomLeft: require("../assets/GUI/expedition-card-9/bottom-left.webp"),
    bottom: require("../assets/GUI/expedition-card-9/bottom.webp"),
    bottomRight: require("../assets/GUI/expedition-card-9/bottom-right.webp"),
  },
  claimed: require("../assets/GUI/claimed.webp"),
  sectionTitle: require("../assets/GUI/text placeholder.png"),
};
